Repository conab-devs/conab-backend, pull requests merged in 2020-09, with the labels that each got.

#33 Autenticação
  .env.example
  app/Components/Errors/InvalidFieldException.php
  app/Components/Errors/UnauthorizedException.php
  app/Http/Controllers/AuthController.php
  app/Providers/AuthServiceProvider.php
  app/Providers/RouteServiceProvider.php
  app/User.php
  composer.json
  composer.lock
  config/app.php
  config/auth.php
  config/jwt.php
  database/factories/UserFactory.php
  routes/api.php
  tests/Feature/AuthTest.php
  tests/Feature/ExampleTest.php
  tests/Unit/AuthTest.php
  tests/Unit/ExampleTest.php
Labels: enhancement

#34 CRUD de administradores da conab.
  .gitignore
  app/Cooperative.php
  app/Http/Controllers/AdminConabController.php
  app/Http/Controllers/UploadController.php
  app/Phone.php
  app/User.php
  composer.json
  composer.lock
  config/filesystems.php
  database/factories/AddressFactory.php
  database/factories/CooperativeFactory.php
  database/factories/PhoneFactory.php
  database/factories/UserFactory.php
  database/migrations/2020_08_26_145318_update_profile_picture_column.php
  routes/api.php
  tests/Feature/AdminConabControllerTest.php
  tests/Feature/UploadControllerTest.php
  tmp/picture_to_tests.jpeg
Labels: enhancement

#35 CRUD da Cooperativa
  .gitignore
  app/Address.php
  app/Cooperative.php
  app/Http/Controllers/CooperativeController.php
  app/Phone.php
  database/factories/AddressFactory.php
  database/factories/CooperativeFactory.php
  database/seeds/CooperativeSeeder.php
  routes/api.php
Labels: enhancement

#39 Consertando Testes e Criando Componentes
  app/Components/AuthHandler.php
  app/Components/Errors/InvalidArgumentException.php
  app/Components/Errors/UnprocessableEntityException.php
  app/Components/Services/PasswordResetService.php
  app/Components/Services/UserService.php
  app/Components/TokenGenerator.php
  app/Http/Controllers/AuthController.php
  app/PasswordReset.php
  app/User.php
  config/database.php
  database/migrations/2020_09_03_101402_create_password_resets_table.php
  database/migrations/2020_09_04_165834_drop_users_table.php
  phpunit.xml
  tests/Feature/AuthTest.php
  tests/Feature/UploadControllerTest.php
  tests/Unit/AuthTest.php
  tests/Unit/PasswordResetServiceTest.php
  tests/Unit/TokenGeneratorTest.php
  tests/Unit/UserServiceTest.php
Labels: bug

#41 Paginação e endpoint para retorna um administrador da conab.
  app/Http/Controllers/AdminConabController.php
  routes/api.php
  tests/Feature/AdminConabControllerTest.php
Labels: enhancement

#48 Fix Relacionamento no Modelo da Cooperativa com o Endereço
  app/Cooperative.php
Labels: bug

#49 URL do avatar e retorno do telefones
  app/Http/Controllers/AdminConabController.php
  app/Http/Controllers/AuthController.php
  app/Http/Controllers/UploadController.php
  app/User.php
  routes/api.php
  tests/Feature/AdminConabControllerTest.php
  tests/Feature/AuthTest.php
  tests/Feature/UploadControllerTest.php
  tests/Unit/AuthTest.php
Labels: enhancement

#50 Configurando url do DAP
  .env.example
  app/Cooperative.php
Labels: enhancement

#43 Forgot password
  .env.example
  app/Components/Auth/AuthHandler.php
  app/Components/Auth/ForgotPasswordHandler.php
  app/Components/Auth/TokenGenerator/JwtGenerator.php
  app/Components/Auth/TokenGenerator/StringGenerator.php
  app/Components/Auth/TokenGenerator/TokenGenerator.php
  app/Components/AuthHandler.php
  app/Components/Errors/InvalidArgumentException.php
  app/Components/Errors/UnauthorizedException.php
  app/Components/Errors/UnprocessableEntityException.php
  app/Components/Services/PasswordResetService.php
  app/Components/Services/UserService.php
  app/Components/TokenGenerator.php
  app/Exceptions/CustomException.php
  app/Exceptions/Handler.php
  app/Exceptions/ServerError.php
  app/Exceptions/UnauthorizedException.php
  app/Http/Controllers/AuthController.php
  app/Http/Requests/Login.php
  app/Http/Requests/ResetPassword.php
  app/Http/Requests/ResetRequest.php
  app/Mail/ResetMail.php
  app/PasswordReset.php
  app/Providers/AppServiceProvider.php
  composer.lock
  config/app.php
  resources/views/Email/resetPassword.blade.php
  routes/api.php
  tests/Feature/AuthTest.php
  tests/Unit/AuthTest.php
  tests/Unit/ForgotPasswordTest.php
  tests/Unit/PasswordResetServiceTest.php
  tests/Unit/TokenGeneratorTest.php
  tests/Unit/UserServiceTest.php
Labels: enhancement

#53 Paginação das cooperativas e busca de por nome
  app/Http/Controllers/CooperativeController.php
Labels: enhancement

#57 Retornando URL Completa
  app/Exceptions/CustomException.php
  app/Exceptions/ServerError.php
  app/Exceptions/UnauthorizedException.php
  app/Http/Controllers/UploadController.php
  app/User.php
  database/factories/UserFactory.php
Labels: enhancement

#58 Deploy no Heroku
  .gitignore
  Procfile
  config/database.php
  routes/api.php
Labels: enhancement, high priority
