Repository conab-devs/conab-backend, pull requests merged in 2020-10, with the labels that each got.

#60 Cooperative Admin Management
  .env.example
  app/Components/Validators/UpdateUser.php
  app/Cooperative.php
  app/Http/Controllers/AdminConabController.php
  app/Http/Controllers/CooperativeAdminController.php
  app/Http/Controllers/CooperativeController.php
  app/Http/Controllers/UserController.php
  app/Http/Kernel.php
  app/Http/Middleware/OnlyConabAdmins.php
  app/Http/Requests/CooperativeAdminStore.php
  app/Providers/AuthServiceProvider.php
  app/User.php
  composer.json
  composer.lock
  database/factories/CooperativeFactory.php
  database/factories/UserFactory.php
  routes/api.php
  storage/app/public/.gitignore
  tests/Feature/AdminConabControllerTest.php
  tests/Feature/AdminCooperativeControllerTest.php
  tests/Feature/AuthTest.php
Labels: enhancement

#61 Release/v1.0.0
  composer.lock
  database/seeds/AdminSeeder.php
  database/seeds/DatabaseSeeder.php
Labels: high priority

#63 chore: remove release command
  Procfile
Labels: high priority

#64 Release/v1.0.0
  .github/ISSUE_TEMPLATE/requisito-feature.md
  .gitignore
  Procfile
  config/database.php
Labels: high priority

#65 chore: add faker to production
  composer.json
  composer.lock
Labels: high priority

#66 chore: add faker to production
  composer.json
  composer.lock
Labels: high priority

#69 improve personalized configurations getting
  config/database.php
Labels: enhancement

#71 Upload de Arquivo no Firebase Storage
  .env.example
  .gitignore
  app/Components/FirebaseStorageAdapter.php
  app/Components/Traits/UploadFirebase.php
  app/Cooperative.php
  app/Http/Controllers/CooperativeController.php
  app/Http/Controllers/UploadController.php
  app/Providers/FirebaseStorageProvider.php
  app/User.php
  composer.json
  composer.lock
  config/app.php
  config/database.php
  tests/Feature/FirebaseStorageAdapterTest.php
  tests/Feature/UploadControllerTest.php
Labels: enhancement, high priority

#74 Release/v1.1.0
  .env.example
  .gitignore
  app/Components/FirebaseStorageAdapter.php
  app/Components/Traits/UploadFirebase.php
  app/Cooperative.php
  app/Http/Controllers/CooperativeController.php
  app/Http/Controllers/UploadController.php
  app/Providers/FirebaseStorageProvider.php
  app/User.php
  composer.json
  composer.lock
  config/app.php
  config/database.php
  database/migrations/2020_10_17_192914_alter_columns_dap_path_and_picture_profile.php
  tests/Feature/FirebaseStorageAdapterTest.php
  tests/Feature/UploadControllerTest.php
Labels: enhancement, high priority

#75 Release/v1.1.0
  app/Http/Controllers/CooperativeController.php
  composer.lock
  database/migrations/2020_10_17_192914_alter_columns_dap_path_and_picture_profile.php
Labels: enhancement, high priority

#70 Feature/manage categories
  app/Category.php
  app/Http/Controllers/CategoryController.php
  composer.lock
  database/factories/CategoryFactory.php
  routes/api.php
  tests/Feature/CategoriesTest.php
Labels: enhancement
